#!/usr/bin/env bash
# Generates the PROJECT's skills from JOCA's skills — single source.
#
# Why it exists: the previous version of the package kept a COPY of each skill
# in templates/claude/skills/. The copies diverged silently — the template's
# `new-issue` lost the "Likely files" section, which is exactly the
# field `plan-waves` depends on to decide parallelism. The package
# installed a broken chain. There is no copy here: the source is read.
#
# Usage: export-skills.sh <project-root> <JOCA_Brain-root> [skill...]

set -euo pipefail

PROJECTO=${1:?usage: export-skills.sh <project> <joca_brain> [skill...]}
BRAIN=${2:?the JOCA_Brain root is missing}
shift 2
SKILLS=("$@")
[ ${#SKILLS[@]} -eq 0 ] && SKILLS=(new-issue write-tests prepare-design validate-design plan-waves)

ORIGEM="$BRAIN/.claude/skills"
DESTINO="$PROJECTO/.claude/skills"

[ -d "$ORIGEM" ] || { echo "error: cannot find $ORIGEM" >&2; exit 1; }
mkdir -p "$DESTINO"

for s in "${SKILLS[@]}"; do
  src="$ORIGEM/$s.md"
  if [ ! -f "$src" ]; then
    echo "error: skill '$s' does not exist in $ORIGEM" >&2
    exit 1
  fi
  dst_dir="$DESTINO/$s"
  dst="$dst_dir/SKILL.md"
  # Overwriting an existing file is irreversible: stop, do not guess.
  if [ -e "$dst" ]; then
    echo "error: $dst already exists — remove or rename it first (I do not overwrite)" >&2
    exit 1
  fi
  mkdir -p "$dst_dir"
  # The "generated" notice has to go in AFTER the frontmatter closes: an HTML
  # comment before the first `---` pushes the YAML down and Claude Code stops
  # recognizing the skill. The file still exists and still looks fine — this
  # defect only shows up when validating the artifact, never when looking at the script.
  #
  # `triggers:` and `chain:` are JOCA conventions and mean nothing in a
  # standalone project — they go. The rest of the frontmatter passes through as is.
  awk -v origem="$s" '
    /^---[[:space:]]*$/ { delim++ }
    /^triggers:|^chain:/ { if (delim == 1) next }
    { print }
    delim == 2 && !avisado {
      print ""
      print "<!-- GENERATED by export-skills.sh from JOCA_Brain/.claude/skills/" origem ".md"
      print "     Do not edit here: edit the source and re-run the script. -->"
      avisado = 1
    }
  ' "$src" > "$dst"
  echo "  $s → .claude/skills/$s/SKILL.md"
done

echo "${#SKILLS[@]} skill(s) exported."
