// GIFs of the "The Office" theme — they replace the sidebar icons, and ONLY with `data-brand="office"`.
//
// You do NOT edit code to put them in. You drop files in `public/brand/office/` with these names:
//
//     dashboard · agentes · definicoes · projectos
//
// The extension can be `.webp`, `.gif` or `.png`, in that order of preference. Giphy serves
// animated `.webp`, which is the lightest of the three (and what its "copy link" gives), so it
// comes first — it is not worth converting to GIF to make the file bigger.
//
// Each one that exists becomes the icon; the missing ones keep the drawn glyph. Nothing needs
// restarting — just reload the page.
//
// ⚠ Why local files and not Giphy links hardcoded here: this repository is PUBLIC, and the
// GIFs from the show are third-party work. A link in the published code makes EVERYONE who
// clones it distribute them; a file in the folder below stays on this machine only — the folder is in
// `.gitignore`. As a side effect, it works offline, which the hotlink does not.
const DIR = '/brand/office/';
/** Order of attempts. First what Giphy gives and is lightest. */
const EXT = ['webp', 'gif', 'png'];

/** Icon name in the sidebar → filename. Only these five accept a GIF. */
export const OFFICE_GIF_FILES: Record<string, string> = {
  'layout-dashboard': 'dashboard',
  terminal: 'agentes',
  // A key separate from the Agents one deliberately: sharing it put the same GIF in both places.
  'terminal-quick': 'sessao',
  settings: 'definicoes',
  folder: 'projectos',
};

/**
 * Cache of the probe result, by icon name. Without this there was one request per EACH instance of the
 * icon (the sidebar draws the same icon on several rows) and the 404 of the ones that do not exist
 * repeated on every render.
 *   undefined = not probed yet · null = does not exist · string = good URL
 */
const cache = new Map<string, string | null>();
const emCurso = new Map<string, Promise<string | null>>();

/**
 * Tries `base.webp`, `base.gif`, `base.png` and returns the first one that loads.
 * `new Image()` instead of fetch: it does not need CORS and it is the same request the `<img>` would
 * make next, so the browser serves it from cache and there is no second trip to the network.
 */
function primeiraQueCarrega(base: string, i = 0): Promise<string | null> {
  if (i >= EXT.length) return Promise.resolve(null);
  const url = `${base}.${EXT[i]}`;
  return new Promise<string | null>((resolve) => {
    const img = new Image();
    img.onload = () => resolve(url);
    img.onerror = () => resolve(null);
    img.src = url;
  }).then((r) => r ?? primeiraQueCarrega(base, i + 1));
}

/** Probes the file once and returns the URL if it exists. */
export function probeOfficeGif(name: string): Promise<string | null> {
  const ficheiro = OFFICE_GIF_FILES[name];
  if (!ficheiro) return Promise.resolve(null);
  if (cache.has(name)) return Promise.resolve(cache.get(name) ?? null);
  const jaVai = emCurso.get(name);
  if (jaVai) return jaVai;

  const p = primeiraQueCarrega(`${DIR}${ficheiro}`).then((r) => {
    cache.set(name, r);
    emCurso.delete(name);
    return r;
  });
  emCurso.set(name, p);
  return p;
}

// ── Pool: one GIF per project / per session ────────────────────────────────────────────────────
//
// Files in `public/brand/office/pool/` numbered from `01`: `01.webp`, `02.webp`, …
// (it also accepts `.gif` and `.png`). The probing stops at the first missing number, so the
// size of the pool is whatever is in the folder — adding or removing files requires no change here.
const POOL_DIR = '/brand/office/pool/';
/** Ceiling of the probing. It only exists so the loop is not infinite if the folder has something odd. */
const POOL_MAX = 60;

let poolPromise: Promise<string[]> | null = null;

/** Pool URLs, in order. Probed ONCE per page load. */
export function loadOfficePool(): Promise<string[]> {
  if (poolPromise) return poolPromise;
  poolPromise = (async () => {
    const encontrados: string[] = [];
    for (let i = 1; i <= POOL_MAX; i++) {
      const url = await primeiraQueCarrega(POOL_DIR + String(i).padStart(2, '0'));
      if (!url) break;
      encontrados.push(url);
    }
    return encontrados;
  })();
  return poolPromise;
}

/**
 * A STABLE choice: the same id always gives the same GIF.
 *
 * "Random" here cannot be `Math.random()` — with a new value on every render the icon changed on
 * every repaint of the sidebar and you never learned to recognize a project by its image. What you want is
 * unpredictable BETWEEN projects and fixed FOR a project: a hash of the id gives exactly that, and
 * it survives a page reload without storing any state.
 */
export function poolIndex(id: string, total: number): number {
  if (total <= 0) return 0;
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (Math.imul(h, 31) + id.charCodeAt(i)) >>> 0;
  return h % total;
}

/**
 * URL of the STILL frame that goes with an animated one (`x.webp` → `x-still.webp`).
 *
 * Generated by a script from the first frame. It is what is shown at rest: a GIF cannot be
 * paused by CSS nor by attribute, so "static until hover" is only done with two images.
 * A side effect worth having on its own: the sidebar now loads ~20 KB per icon instead of 0.5-2 MB, and
 * the animated file is only requested from the network when the mouse passes over it.
 */
export function stillFor(url: string): string {
  return url.replace(/\.(webp|gif|png)$/i, '-still.webp');
}
