// Persistence layer for projects, per-project memory, and UI settings — all JSON files under
// ../../data. Self-contained: paths derive from __dirname. Exports the generic readJsonFile/
// writeJsonFile helpers (reused by the knowledge-graph route) plus typed load/save functions.
import path from 'path';
import fs from 'fs';

// Optional icon of a project or of a group. Two shapes only, because they are the two the UI knows
// how to draw; with no icon the UI falls back to the first 2 letters of the name (no default to persist).
//   'image' → `value` is the NAME of the file in data/icons, always generated by the server (a UUID +
//             extension). Never the name the client sent — that would be direct path traversal.
//   'emoji' → `value` is the emoji itself (a single grapheme cluster).
export interface ProjectIcon {
  type: 'image' | 'emoji';
  value: string;
}

export interface Project {
  id: string;
  name: string;
  path: string;
  color?: string;
  icon?: ProjectIcon;
  githubRepo?: string;
  archived?: boolean;
  order?: number;
  // Visual-only bundling in the sidebar (see project-groups-store.ts) — has no effect on the
  // project itself. undefined = not in any group.
  groupId?: string;
  // What the project is, in the owner's own words. Goes into the brief of this project's tasks.
  // the closest thing it has to "what is this project and what are we trying to do".
  description?: string;
  // ⚠ Written by the UI but read by no logic at all today — it lost its consumer when the
  // project manager was removed.
  // is something to read.
  hasCode?: boolean;
}

export interface ProjectMemory {
  projectId: string;
  color?: string;
  path?: string;
  recentSessions: string[];
  favoriteSkills: string[];
  favoriteAgents: string[];
  quickCommands: string[];
  openFiles: string[];
  updatedAt: string;
}

export type LlmProvider = 'claude' | 'ollama';

export interface UiSettings {
  skipPermissions: boolean;
  theme?: 'dark' | 'light';        // theme ALREADY resolved (legacy + quick read); default dark
  themeMode?: 'dark' | 'light' | 'auto';  // the user's choice; 'auto' = switches by the hour
  themeDayStart?: string;          // "HH:MM" at which it turns light (only counts in 'auto')
  themeNightStart?: string;        // "HH:MM" at which it turns dark (only counts in 'auto')
  defaultCli?: string;             // CLI used by new terminals: claude (default) | codex | agy | opencode
  // Brand theme ("Custom Themes"): only name + logo + colors on the client. The backend stores it so
  // the choice follows the user to another machine — nothing on the server changes behavior.
  brandTheme?: string;
}

// Overridable by `JOCA_DATA_DIR`. It exists because of the tests: `notifications.test.ts` does
// `fs.rmSync` on files in THIS folder — pointed at the real data,
// running `npm test` deleted the user's real notifications. With the override,
// vitest writes to a temporary folder and the tests can no longer touch real data.
export const DATA_DIR = process.env.JOCA_DATA_DIR || path.join(__dirname, '../../data');
const PROJECTS_FILE = path.join(DATA_DIR, 'projects.json');
const PROJECT_MEMORY_FILE = path.join(DATA_DIR, 'project-memory.json');
const UI_SETTINGS_FILE = path.join(DATA_DIR, 'ui-settings.json');

const DEFAULT_UI_SETTINGS: UiSettings = { skipPermissions: false };

export function readJsonFile<T>(filePath: string, fallback: T): T {
  try { return JSON.parse(fs.readFileSync(filePath, 'utf8')) as T; } catch { return fallback; }
}

// Atomic write: write to a temp file then rename over the target. rename is atomic on the same
// volume, so a process kill (stop.bat / terminate) mid-write can never leave a half-written or
// "frozen" file that the next boot fails to parse. Generic over any string payload (JSON, md, jsonl).
export function writeFileAtomic(filePath: string, data: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const tmp = `${filePath}.tmp`;
  fs.writeFileSync(tmp, data);
  fs.renameSync(tmp, filePath);
}

export function writeJsonFile<T>(filePath: string, data: T) {
  writeFileAtomic(filePath, JSON.stringify(data, null, 2));
}

export function loadUiSettings(): UiSettings {
  return { ...DEFAULT_UI_SETTINGS, ...readJsonFile<Partial<UiSettings>>(UI_SETTINGS_FILE, {}) };
}

export function saveUiSettings(settings: UiSettings) {
  writeJsonFile(UI_SETTINGS_FILE, settings);
}

export function loadProjects(): Project[] {
  try { return JSON.parse(fs.readFileSync(PROJECTS_FILE, 'utf8')); }
  catch (e) {
    // Only a corrupt/locked existing file is a real problem — a missing file (first run) is normal.
    if (fs.existsSync(PROJECTS_FILE)) console.error('[project-store] could not read projects.json:', e);
    return [];
  }
}

export function saveProjects(projects: Project[]) {
  writeJsonFile(PROJECTS_FILE, projects);
}

export function loadProjectMemory(): Record<string, ProjectMemory> {
  return readJsonFile<Record<string, ProjectMemory>>(PROJECT_MEMORY_FILE, {});
}

export function saveProjectMemory(memory: Record<string, ProjectMemory>) {
  writeJsonFile(PROJECT_MEMORY_FILE, memory);
}
