#!/usr/bin/env bash
# check-skill-paths.sh — Guard against reintroducing broken skill paths.
#
# Current flat structure: .claude/skills/<name>.md
# Broken legacy paths (do NOT allow):
#   - placeholder:   skills/SKILL.md            (no name — the 19-file bug)
#   - old nested:    skills/<category>/<name>/SKILL.md
#
# Valid exceptions (NOT a bug):
#   - skills/created-skills/<name>/SKILL.md  — convention for skills generated by /create-skill
#   - lines with placeholders in <...>        — documentation, not real paths
#
# Usage:
#   bash .claude/scripts/check-skill-paths.sh <file>      # 1 file (PostToolUse hook)
#   bash .claude/scripts/check-skill-paths.sh --all        # sweeps the whole repo (manual)
#
# Exits 0 if clean, 2 if it finds broken paths.
# No argument (e.g. empty $TOOL_INPUT_FILE_PATH) → no-op, exit 0.

set -uo pipefail

TARGET="${1:-}"

PAT_PLACEHOLDER='skills/SKILL\.md'
PAT_NESTED='skills/[^/]+/[^/]+/SKILL\.md'

# Filters common false positives (created-skills exception + <...> placeholders).
filter_fp() { grep -v -e 'skills/created-skills/' -e '<[A-Za-z_]*>'; }

scan_one() {  # $1 = file
  grep -nE -e "$PAT_PLACEHOLDER" -e "$PAT_NESTED" "$1" 2>/dev/null | filter_fp || true
}

scan_repo() {
  if command -v rg >/dev/null 2>&1; then
    rg -n --no-heading \
      --glob '!.git/**' --glob '!node_modules/**' --glob '!vendor/**' \
      --glob '!graphify-out/**' --glob '!memory/feedback/**' \
      --glob '!**/check-skill-paths.sh' \
      -e "$PAT_PLACEHOLDER" -e "$PAT_NESTED" . 2>/dev/null | filter_fp || true
  else
    grep -rnE \
      --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=vendor \
      --exclude-dir=graphify-out --exclude-dir=feedback \
      --exclude='check-skill-paths.sh' \
      -e "$PAT_PLACEHOLDER" -e "$PAT_NESTED" . 2>/dev/null | filter_fp || true
  fi
}

# --- dispatch ---
if [[ -z "$TARGET" ]]; then
  # Hook called with no path (empty var) → do not block.
  exit 0
fi

if [[ "$TARGET" == "--all" ]]; then
  HITS="$(scan_repo)"
  MODE="all"
else
  # Per-file. Exempts the guard itself (it contains the patterns as documentation).
  case "$TARGET" in
    *check-skill-paths.sh) exit 0 ;;
  esac
  [[ -f "$TARGET" ]] || exit 0   # non-existent/deleted file → no-op
  HITS="$(scan_one "$TARGET")"
  MODE="file"
fi

if [[ -n "$HITS" ]]; then
  echo "✗ Broken skill path detected (legacy)."
  echo "  Correct structure (flat): .claude/skills/<name>.md"
  echo "  Forbidden: 'skills/SKILL.md' and nested 'skills/<cat>/<name>/SKILL.md'"
  echo "  (Valid exception: skills/created-skills/<name>/SKILL.md)"
  echo "  Occurrences:"
  echo "$HITS" | sed 's/^/    /'
  exit 2
fi

[[ "$MODE" == "all" ]] && echo "✓ No broken skill paths."
exit 0
